language: node_js
node_js:
- node
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: FLrKJOim23L8cv/zGma2s+9TvhZscbJD4TvRzwcBtIUro31rylAmalZrLCJg0GiLhW8qTjyP/8JXJnWqYq9AZxql3Zj7ZogymfS1QWy1eDAb6LTMQShdHWlXKc9q1TiatxaTMQhYy84sk88LaVR79cViSrYt0GLx2x4iVexqqD0jiEGJe31eiYBfNhBbOCklqft1OFkJVlo6xA3p4MAs/KQEvXHP0mwMkT3ngiXpJM1zsd7eQCaLcIDwCJsMo38cMDLeQvWjP0q2uoKO4IZdhulk6YORoJ7GBf8oJln78B3mBN1cjReZdqtMD3HxRmVOSToSZFAF14DcEDmZfMDp4nG50je96eUHqxvMJ5K2jCVMd++FEy1q9VwpWkW9VnilwVCj/Yi699+Bq0QESSXzWz8wF9suTN3bWMPRac38mjf3SB2Yhi+0E/b75FsE8uCYCWTWMGy5fgqa11GmB27ABvM4SdpAGn9PnSq/d6urCYuut1r3+pDXcZqJ13pOgCm47VgDt09pRyvGYFUGzEMk9NGctuXI5HGoY5BsyR0YXh8ZFFF+W654b0r3LiBG7UfQvRY03d3Cr1sR//QmoMBtl55TdyGwB+r2A13bQaj/VQtsOgymoP16J8PzON7cexVYbW9xGbsEdF9DWQ5hx8NxLJOK68Idm860MCKMPrZBUyE=
