language: node_js
node_js:
- node
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: bpTQVgOD+VdjVf8kmT+gZgNEs4cMwqSuMXNoGVDu6aUPyG80WeJhwgzdijpANSJVoT/CFfoYRejjDH3cZjjavt6wvooRHsll8LT6TkHkKW+blfIYkx/oRgJ7wTAozRpYbEkIqdBhmRAMoX0fuNqDozImEXNC/WfhDFCdOSkbHQPg4d+O8QhQgsblmnbcQunz13tmW6fbWDG42ohaNTbhaM9hCeyyWM2HkcdGRsEILM8YTn4ZEC7t043xVZzKoKtsqWeujU5RGeuF1WyfQSLG8cO4PA/SMDpNwPn+21ZHy4/Fd4Xb5Mp1VnUL9N2scBTe9MQX30IzTTmZM36S4y22dO6vSoDmExrzotTQsenudws79VvqBc/cm6ZS05mbaMX1Kxpzav/yiEYBGPjB02oIf/SAbR2wjluW0rZhutQmQpJas4YJypi5SEtp+TTsNDzwPeBm+YdCiZjt5dy8cgyfqCg8LVjLGYfxN+fnpFNbm7FgqbawH9ya1OoRF3CoBUeeNDLPdG+SNvdExYda6ZP7K0jOEEbr1jnV9t4rzSpjm8KpaFhavuEzQCA/DFoD8OIkBrFGsN5usyTiUAIBsYd7/4RIvXQwNK8RCME4+JdmeteyRV3UO3ItL4h6VhqPBiC/veSyIVfJ2BUp4NYbzKohOhN4jKngrLby5p23QKeDFEo=
